[package]
authors = ["David Barnett <david@barnett.net.nz>"]
name = "lambda_hit"
version = "0.1.0"
[dependencies]
clap = "2.26.2"
reqwest = "0.7.3"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
