CC:=gcc
CFALGS:=-std=c89

all: q5 q6 q7 q8

q5: q5.c
	$(CC) $(CFLAGS) -o $@ $^

q6: q6.c
	$(CC) $(CFLAGS) -o $@ $^

q7: q7.c
	$(CC) $(CFLAGS) -o $@ $^

q8: q8.c
	$(CC) $(CFLAGS) -o $@ $^

clean:
	rm q5 q6 q7 q8
