CC:=gcc
CFLAGS:=-std=c89

all: q1 q2 q3 q4

q1: q1.c
	$(CC) $(CFLAGS) -o $@ $^

q2: q2.c
	$(CC) $(CFLAGS) -o $@ $^

q3: q3.c
	$(CC) $(CFLAGS) -o $@ $^

q4: q4.c
	$(CC) $(CFLAGS) -o $@ $^

clean:
	@rm q1 q2 q3 q4
