#!/bin/sh
#
DURATION="10mins"
EVERY="10"			# seconds
rm -rf data/
mkdir data


echo "#define MAXHOPS 4" > hops.h
for map in "NEWZEALAND.MAP" "WORLD.MAP" "NZ AUS.MAP" "NORTH ISLAND.MAP"
do
    echo "#include \"maps/${map}\"" > map.h
    for f in 1 2 3
    do
        cnet -W -q -T -e $DURATION -s -f ${EVERY}secs FLOODING$f	| \
            grep 'Efficiency'						| \
            cut -d: -f 2						| \
            awk "{ printf(\"%d %s\n\", ++i * $EVERY, \$1); }" > data/result-$map.flood$f
    done

    map_low=$(echo ${map} | awk '{print tolower($0)}' | sed -e 's/_/\\_/')
    echo ${map_low}

    gnuplot <</EOF

    map = "${map}"

    set title sprintf("Comparison of 3 flooding protocols - %s", map)
    set xlabel "Running time (seconds)"
    set ylabel "Delivery efficiency (%)"

    set grid
    set yrange [0:]


    set terminal png size 800,600 enhanced font "Helvetica,14"
    set output sprintf("../res/%s-plot.png", map)
    plot	\
        sprintf("data/result-%s.flood1", map)		title "flooding1" with linespoints, \
        sprintf("data/result-%s.flood2", map)		title "flooding2" with linespoints, \
        sprintf("data/result-%s.flood3", map)		title "flooding3" with linespoints
/EOF
done

